import { z } from 'zod';

const portSchema = z.coerce.number().int().min(1).max(65535);

export const envSchema = z.object({
  // App
  NODE_ENV: z.enum(['development', 'test', 'staging', 'production']).default('development'),
  PORT: portSchema.default(3002),
  API_VERSION: z.string().default('v1'),
  APP_NAME: z.string().default('bomboli-api'),
  APP_URL: z.string().url().default('http://localhost:3002'),
  ALLOWED_ORIGINS: z.string().default('http://localhost:3002'),

  // Database
  DATABASE_URL: z.string().url(),
  DIRECT_URL: z.string().url().optional(),

  // Supabase
  SUPABASE_URL: z.string().url(),
  SUPABASE_ANON_KEY: z.string().min(1),
  SUPABASE_SERVICE_ROLE_KEY: z.string().min(1),
  SUPABASE_JWT_SECRET: z.string().min(1),
  // Shared secret presented by Supabase Database Webhooks in the
  // Authorization header. Generated by the operator; not derivable.
  SUPABASE_WEBHOOK_SECRET: z.string().min(16),

  // Redis
  REDIS_URL: z.string().default('redis://localhost:6381'),
  REDIS_HOST: z.string().default('localhost'),
  REDIS_PORT: portSchema.default(6381),
  REDIS_PASSWORD: z.string().optional().default(''),

  // JWT (backend-issued — currently unused but reserved for future flows)
  JWT_SECRET: z.string().min(16),
  JWT_EXPIRATION: z.string().default('7d'),

  // Rate limiting
  RATE_LIMIT_TTL: z.coerce.number().int().positive().default(60),
  RATE_LIMIT_MAX: z.coerce.number().int().positive().default(100),

  // Idempotency (Redis-backed dedupe for POST endpoints)
  IDEMPOTENCY_TTL_HOURS: z.coerce.number().int().positive().default(24),

  // Observability
  SENTRY_DSN: z.string().optional().default(''),
  SENTRY_TRACES_SAMPLE_RATE: z.coerce.number().min(0).max(1).default(0),
  METRICS_TOKEN: z.string().optional().default(''),
});

export type Env = z.infer<typeof envSchema>;

export function validateEnv(config: Record<string, unknown>): Env {
  const parsed = envSchema.safeParse(config);

  if (!parsed.success) {
    const formatted = parsed.error.errors
      .map((err) => `  - ${err.path.join('.')}: ${err.message}`)
      .join('\n');
    throw new Error(`Environment validation failed:\n${formatted}`);
  }

  return parsed.data;
}
